In [4]:
from array import *
First = array('i', [1,2,3,4,5,6])

In [5]:
First

array('i', [1, 2, 3, 4, 5, 6])

In [7]:
print(First[0])

1


In [9]:
First.append(18)

In [10]:
First

array('i', [1, 2, 3, 4, 5, 6, 18])

In [11]:
First.insert(0, 21)

In [12]:
First

array('i', [21, 1, 2, 3, 4, 5, 6, 18])

In [4]:
import numpy as np
twod_array = np.array([[1,2,3,4],[4,5,6,7]])
print(twod_array)

[[1 2 3 4]
 [4 5 6 7]]


In [11]:
new_twod_array = np.insert(twod_array, 0, [[9,9,9,9]], axis = 0)
new_twod_array

array([[9, 9, 9, 9],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
numdays = int(input('Total no. of days:'))
total = 0
for i in range(1, numdays+1):
   nextday =  int(input(f'What is the {i} days high temp:'))
   total = total + nextday

avg = round(total/numdays)
print(f'Average Temperature = {avg}')


Average Temperature = 30
